
[functions.invite-user]
enabled = true
verify_jwt = false
import_map = "./functions/invite-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/invite-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/invite-user/*.html" ]

[functions.create-club]
enabled = true
verify_jwt = false
import_map = "./functions/create-club/deno.json"
entrypoint = "./functions/create-club/index.ts"

[functions.bootstrap-super-admin]
enabled = true
verify_jwt = false
import_map = "./functions/bootstrap-super-admin/deno.json"
entrypoint = "./functions/bootstrap-super-admin/index.ts"

[functions.seed-test-club]
enabled = true
verify_jwt = false
import_map = "./functions/seed-test-club/deno.json"
entrypoint = "./functions/seed-test-club/index.ts"

[functions.expand-test-club]
enabled = true
verify_jwt = false
import_map = "./functions/expand-test-club/deno.json"
entrypoint = "./functions/expand-test-club/index.ts"

[functions.expand-test-club-athletes]
enabled = true
verify_jwt = false
import_map = "./functions/expand-test-club-athletes/deno.json"
entrypoint = "./functions/expand-test-club-athletes/index.ts"

[functions.request-password-reset-notice]
enabled = true
verify_jwt = false
import_map = "./functions/request-password-reset-notice/deno.json"
entrypoint = "./functions/request-password-reset-notice/index.ts"

[functions.admin-reset-user-password]
enabled = true
verify_jwt = false
import_map = "./functions/admin-reset-user-password/deno.json"
entrypoint = "./functions/admin-reset-user-password/index.ts"

[functions.delete-club]
enabled = true
verify_jwt = false
import_map = "./functions/delete-club/deno.json"
entrypoint = "./functions/delete-club/index.ts"

[functions.promote-to-global]
enabled = true
verify_jwt = false
import_map = "./functions/promote-to-global/deno.json"
entrypoint = "./functions/promote-to-global/index.ts"

[functions.send-push-notification]
enabled = true
verify_jwt = false
import_map = "./functions/send-push-notification/deno.json"
entrypoint = "./functions/send-push-notification/index.ts"
