// SINAMA SETİ — motor ayarlanırken ASLA kullanılmayan, gerçek kullanıcıların
// yazabileceği serbest cümleler. Amaç: motorun görmediği sorulara ne kadar
// genelleştiğini dürüstçe ölçmek. Başarısız olanlar betiği durdurmaz, raporlanır.
// [rol, soru, beklenen giriş id'lerinden biri (dizi olabilir)]
module.exports = [
  ["A", "sporcuların telefon numaralarını nereden görürüm", ["sporcu-detay", "sporcu-listesi", "veli-ara"]],
  ["A", "bir sporcu kulüpten ayrıldı ne yapmalıyım", ["sporcu-duzenle-sil"]],
  ["A", "antrenörün izinli olduğunu nasıl kaydederim", ["antrenor-izin"]],
  ["A", "salonun kapasitesini değiştirmek istiyorum", ["salon-ekle"]],
  ["A", "yeni bir grup kurmak istiyorum", ["grup-ekle"]],
  ["A", "her ay otomatik aidat oluşsun istiyorum", ["aidat-plani"]],
  ["A", "veli parayı yatırdığını söylüyor ama görünmüyor", ["odendi-isaretle", "veli-aidat-ode"]],
  ["A", "kulübün logosunu nasıl koyarım", ["logo-isim"]],
  ["A", "mağazadaki siparişleri görmek istiyorum", ["magaza-siparis-yonet"]],
  ["A", "etkinliğe kimler kayıt olmuş", ["etkinlik-kayit-yonet"]],
  ["A", "velilerin hepsine haber vermek istiyorum", ["duyuru-yapma"]],
  ["A", "şifresini unutan bir veli var", ["kullanicilar"]],
  ["A", "iki branşımız var ikisinin aidatı farklı", ["sabit-aidat", "aidat-plani"]],
  ["A", "gelir gider tablosunu görmek istiyorum", ["finansal-dokuman"]],
  ["C", "bugün kaç kişi geldi işaretlemem lazım", ["yoklama-alma"]],
  ["C", "antrenmanı yanlış saate koymuşum", ["antrenman-sil", "antrenman-ekle"]],
  ["C", "gelecek hafta için antrenman programı yapmak istiyorum", ["haftalik-plan", "antrenman-ekle"]],
  ["C", "rakip takımı ve maç saatini girmek istiyorum", ["musabaka-ekle"]],
  ["C", "sporcunun sıçrama ölçümünü kaydetmek istiyorum", ["olcum-kaydet"]],
  ["C", "bütün gruba aynı testi yaptırdım hepsini girmek istiyorum", ["olcum-toplu"]],
  ["C", "sporcu için özel bir not bırakmak istiyorum", ["kocluk-notu"]],
  ["C", "velinin telefonuna nasıl ulaşırım", ["veli-ara"]],
  ["C", "bu sporcunun ayağı incinmiş", ["sakatlik"]],
  ["C", "hangi sporcular gelemeyeceğini bildirdi", ["yoklama-durum-cesitleri"]],
  ["P", "çocuğum bu hafta hasta antrenmana gitmeyecek", ["gelemeyecegim"]],
  ["P", "okul servisi yüzünden geç kalacağız", ["gelemeyecegim", "yoklama-durum-cesitleri"]],
  ["P", "aidatı bankadan yatırdım ne yapmam lazım", ["veli-aidat-ode"]],
  ["P", "makbuzumu almak istiyorum", ["veli-aidat-ode"]],
  ["P", "çocuğuma tişört almak istiyorum", ["magaza-siparis"]],
  ["P", "yaz kampına kaydettirmek istiyorum", ["etkinlik-kayit"]],
  ["P", "kızımın gelişimini görmek istiyorum", ["olcum-gorme", "sporcu-takibi"]],
  ["P", "antrenörle konuşmak istiyorum", ["mesaj-gonder"]],
  ["P", "uygulama bildirim göndermiyor", ["bildirim-izni"]],
  ["P", "oğlumun kaydını bir süre dondurmak istiyorum", ["kayit-dondurma"]],
  ["S", "bugünkü idmanı puanlamak istiyorum", ["rpe-doldurma"]],
  ["S", "sabah uyku bilgilerimi girmek istiyorum", ["checkin-doldurma"]],
  ["S", "fitness çalışmamı kaydetmek istiyorum", ["fitness-sporcu-bireysel", "fitness-sporcu-grup-programi"]],
  ["S", "maç ne zaman ve saat kaçta", ["takvim-veli-sporcu"]],
  ["S", "arkadaşlarımla yazışabilir miyim", ["mesaj-kimle", "mesaj-gonder"]],
  ["S", "paylaştığım fotoğraf yayınlanmadı", ["sosyal-onay-bekliyor"]],
  ["X", "yeni kulübün kaydını onaylamak istiyorum", ["sa-abonelik"]],
  ["X", "uygulamayı bakıma almak istiyorum", ["bakim-modu", "sa-sistem-ayarlari"]],
  ["ALL", "bu uygulamada neler yapabilirim", ["alt-menu", "asistan-nedir", "roller-ozet"]],
  ["ALL", "telefonumu değiştirdim yeniden giriş yapmam gerekiyor mu", ["giris-yapma", "hesap-kilitlendi"]],
];
