// Asistan'ın "💡 Örnek Sorular" listesi — her rol için TAM 20 soru.
// id: kılavuz girişi, q: kullanıcıya gösterilen ve dokununca sorulan soru.
// build-manual.js her sorunun gerçekten kendi girişini bulduğunu doğrular.

const SAMPLES = {
  A: [
    ["sporcu-ekle", "Yeni bir sporcu nasıl eklerim?"],
    ["sporcu-hesap-baglama", "Veliye giriş hesabı nasıl açarım?"],
    ["sporcu-excel", "Excel'den toplu sporcu nasıl aktarırım?"],
    ["antrenor-gruba-ata", "Antrenörü gruba nasıl atarım?"],
    ["koordinator-ata", "Branş koordinatörü nasıl atanır?"],
    ["antrenman-ayarlari", "Yoklama süresini nasıl değiştiririm?"],
    ["aidat-plani", "Sporcuya aidat planı nasıl oluşturulur?"],
    ["kullanicilar", "Bir kullanıcının şifresini nasıl sıfırlarım?"],
    ["duyuru-yapma", "Duyuruyu nasıl yayınlarım?"],
    ["antrenor-avans", "Antrenöre avans nasıl veririm?"],
    ["antrenor-odeme-plani", "Antrenör maaş planı nasıl oluşturulur?"],
    ["banka-bilgisi", "Velilere gösterilecek IBAN'ı nereye girerim?"],
    ["etkinlik-olustur", "Etkinlik nasıl oluşturulur?"],
    ["magaza-urun-ekle", "Mağazaya ürün nasıl eklerim?"],
    ["checkin-ayar", "Günlük check-in'i nasıl kapatırım?"],
    ["rpe-ayar", "Zorluk derecesi süresini nasıl ayarlarım?"],
    ["kayit-dondurma-ayar", "Kayıt dondurma özelliğini nasıl kapatırım?"],
    ["sabit-aidat", "Branş aidat ücretini nasıl güncellerim?"],
    ["finansal-dokuman", "Gelir gider raporunu Excel'e nasıl aktarırım?"],
    ["rozet-esik", "Rozet eşiklerini nasıl değiştiririm?"],
  ],
  K: [
    ["sporcu-ekle", "Yeni bir sporcu nasıl eklerim?"],
    ["sporcu-hesap-baglama", "Veliye giriş hesabı nasıl açarım?"],
    ["yoklama-alma", "Yoklama nasıl alınır?"],
    ["haftalik-plan", "Haftalık antrenman planı nasıl oluştururum?"],
    ["antrenman-ekle", "Tek seferlik antrenman nasıl eklerim?"],
    ["musabaka-ekle", "Maç kadrosunu nasıl seçerim?"],
    ["musabaka-sonuc", "Maç sonucunu nasıl girerim?"],
    ["antrenor-gruba-ata", "Antrenörü gruba nasıl atarım?"],
    ["salon-yetkilisi", "Salon yetkilisi nasıl atanır?"],
    ["aidat-plani", "Sporcuya aidat planı nasıl oluşturulur?"],
    ["odendi-isaretle", "Aidatı ödendi olarak nasıl işaretlerim?"],
    ["duyuru-yapma", "Branşıma duyuru nasıl gönderirim?"],
    ["rozet-esik", "Şampiyon rozeti nasıl veririm?"],
    ["olcum-toplu", "Test grubuyla toplu ölçüm nasıl girilir?"],
    ["fitness-grup-programi", "Fitness programını nasıl yayınlarım?"],
    ["etkinlik-olustur", "Etkinlik nasıl oluştururum?"],
    ["magaza-urun-ekle", "Mağazaya ürün nasıl eklerim?"],
    ["sosyal-onay", "Sporcu paylaşımlarını nasıl onaylarım?"],
    ["checkin-takip", "Sporcuların check-in durumunu nasıl görürüm?"],
    ["sifre-degistir", "Şifremi nasıl değiştiririm?"],
  ],
  C: [
    ["yoklama-alma", "Yoklama nasıl alınır?"],
    ["yoklama-zaman-penceresi", "Yoklama neden açılmıyor?"],
    ["antrenman-ekle", "Antrenman nasıl eklerim?"],
    ["haftalik-plan", "Haftalık antrenman planı nasıl oluştururum?"],
    ["musabaka-ekle", "Maç kadrosunu nasıl seçerim?"],
    ["musabaka-sonuc", "Maç sonucunu nasıl girerim?"],
    ["sporcu-listesi", "Sporcularımı nerede görürüm?"],
    ["sporcu-ekle", "Yeni sporcu nasıl eklerim?"],
    ["sakatlik", "Sporcunun sakatlığını nasıl bildiririm?"],
    ["kocluk-notu", "Sporcu için koç notu nasıl yazarım?"],
    ["olcum-kaydet", "Performans ölçümü nasıl kaydederim?"],
    ["olcum-toplu", "Test grubuyla toplu ölçüm nasıl girilir?"],
    ["fitness-egzersiz-kaydet", "Sporcunun kaldırdığı ağırlığı nasıl kaydederim?"],
    ["fitness-grup-programi", "Fitness programını nasıl yayınlarım?"],
    ["fitness-grubu", "Fitness grubu nasıl oluşturulur?"],
    ["checkin-takip", "Sporcuların check-in durumunu nasıl görürüm?"],
    ["veli-ara", "Veliye nasıl ulaşırım?"],
    ["yoklama-durum-cesitleri", "Geç kaldı ve raporlu ne demek?"],
    ["kayit-dondurma", "Sporcunun kaydını nasıl dondururum?"],
    ["sosyal-paylas", "Fotoğrafı nasıl paylaşırım?"],
  ],
  P: [
    ["cocugumun-profili", "Çocuğumun profilini nasıl görürüm?"],
    ["veli-hesap-cikis", "Birden fazla çocuğum var, hepsi tek hesapta mı?"],
    ["yoklama-durumu", "Çocuğum antrenmana geldi mi nasıl görürüm?"],
    ["takvim-veli-sporcu", "Antrenman saatlerini nereden görürüm?"],
    ["gelemeyecegim", "Çocuğum antrenmana gelemeyecekse nasıl bildiririm?"],
    ["veli-aidat-ode", "Aidatı nasıl öderim?"],
    ["magaza-siparis", "Mağazadan forma nasıl sipariş ederim?"],
    ["etkinlik-kayit", "Etkinliğe nasıl kayıt yaptırırım?"],
    ["etkinlik-kayitlarim", "Etkinlik kaydımı nasıl iptal ederim?"],
    ["kayit-dondurma", "Kaydı geçici olarak nasıl dondururum?"],
    ["olcum-gorme", "Çocuğumun test sonuçlarını nereden görürüm?"],
    ["mesaj-gonder", "Antrenöre nasıl mesaj atarım?"],
    ["mesaj-kimle", "Kimlerle mesajlaşabilirim?"],
    ["bildirim-zili", "Bildirimlerimi nerede görürüm?"],
    ["sifre-degistir", "Şifremi nasıl değiştiririm?"],
    ["sifremi-unuttum", "Şifremi unuttum ne yapmalıyım?"],
    ["kisisel-bilgiler", "Telefon numaramı nasıl güncellerim?"],
    ["rozet-nedir", "Rozetler nasıl kazanılır?"],
    ["destek", "Sorun yaşarsam nereden yardım alırım?"],
    ["sporcu-gorunmuyor", "\"Bağlı bir sporcu bulunamadı\" hatası ne demek?"],
  ],
  S: [
    ["sporcu-takibi", "Gelişimimi nereden takip ederim?"],
    ["yoklama-durumu", "Kaç antrenmana katıldığımı nasıl görürüm?"],
    ["takvim-veli-sporcu", "Antrenman ve maç takvimini nasıl görürüm?"],
    ["gelemeyecegim", "Antrenmana gelemeyeceğimi nasıl bildiririm?"],
    ["checkin-doldurma", "Günlük check-in nasıl doldurulur?"],
    ["rpe-doldurma", "Antrenman zorluk derecesini nasıl girerim?"],
    ["olcum-gorme", "Test sonuçlarımı nereden görürüm?"],
    ["fitness-sporcu-bireysel", "Bireysel fitness programı nasıl oluşturulur?"],
    ["fitness-sporcu-grup-programi", "Antrenörün yayınladığı programı nasıl tamamlarım?"],
    ["beslenme-genel", "Beslenme önerilerini nereden görürüm?"],
    ["rozet-nedir", "Rozetler nasıl kazanılır?"],
    ["sosyal-paylas", "Sosyal alana fotoğraf nasıl paylaşırım?"],
    ["sosyal-onay-bekliyor", "Paylaşımım neden görünmüyor?"],
    ["mesaj-gonder", "Antrenörüme nasıl mesaj atarım?"],
    ["mesaj-kimle", "Kimlerle mesajlaşabilirim?"],
    ["bildirim-zili", "Bildirimlerimi nerede görürüm?"],
    ["takvime-ekle-kullanici", "Antrenmanları telefon takvimime nasıl eklerim?"],
    ["magaza-sporcu", "Mağazadan neden sipariş veremiyorum?"],
    ["etkinlik-gorme", "Etkinlikleri nerede görürüm?"],
    ["sifre-degistir", "Şifremi nasıl değiştiririm?"],
  ],
  X: [
    ["sa-genel", "Süper Admin ana sayfasında neler var?"],
    ["sa-kulupler", "Bir kulübü nasıl silerim?"],
    ["sa-abonelik", "Kulüp aboneliğini nasıl onaylarım?"],
    ["sa-finans-rapor", "X-NETIC gelir gider kaydı nasıl tutulur?"],
    ["sa-duyuru", "Tüm kulüp yöneticilerine duyuru nasıl gönderirim?"],
    ["sa-kutuphane", "Ortak egzersiz ve test kütüphanesini nasıl yönetirim?"],
    ["sa-sistem-ayarlari", "Abonelik fiyatını nasıl değiştiririm?"],
    ["sa-ekranlar", "Bir rolün ana sayfasını nasıl önizlerim?"],
    ["sa-mesaj", "Kulüp yöneticisine nasıl mesaj atarım?"],
    ["giris-yapma", "Uygulamaya nasıl giriş yaparım?"],
    ["sifremi-unuttum", "Şifremi unuttum ne yapmalıyım?"],
    ["gecici-sifre", "Geçici şifreyle ilk girişte ne olur?"],
    ["biyometrik-kilit", "Face ID neden soruyor?"],
    ["bakim-modu", "Bakım modunu nasıl açarım?"],
    ["cikis-yapma", "Nasıl çıkış yaparım?"],
    ["kisisel-bilgiler", "Kişisel bilgilerimi nasıl güncellerim?"],
    ["giris-bilgisi-degistir", "Giriş e-postamı nasıl değiştiririm?"],
    ["sifre-degistir", "Şifremi nasıl değiştiririm?"],
    ["destek", "Sorun yaşarsam nereden yardım alırım?"],
    ["roller-ozet", "Hangi rol ne yapabilir?"],
  ],
};

// Gerileme testleri: kullanıcıların gerçekte yazabileceği serbest cümleler.
// [rol harfi, soru, beklenen giriş id]
const NATURAL_TESTS = [
  ["A", "sporcu silmek istiyorum", "sporcu-duzenle-sil"],
  ["A", "yeni antrenör eklemek istiyorum", "antrenor-ekle"],
  ["A", "antrenörün maaşını nasıl tanımlarım", "antrenor-odeme-plani"],
  ["A", "kulüp logosunu değiştirmek istiyorum", "logo-isim"],
  ["A", "veliler ödeme yapınca ne olur", "odendi-isaretle"],
  ["A", "aidat gecikince veliye bildirim gider mi", "odendi-isaretle"],
  ["A", "kullanıcı şifresini unutmuş", "kullanicilar"],
  ["A", "branş nasıl eklenir", "brans-ekle"],
  ["A", "salon nasıl eklenir", "salon-ekle"],
  ["A", "grup nasıl oluşturulur", "grup-ekle"],
  ["A", "yönetici ana sayfasında neler var", "anasayfa-yonetici"],
  ["A", "kutucukları gizlemek istiyorum", "ana-sayfa-ozellikleri"],
  ["A", "zorluk derecesi bildirimi gelmesin", "rpe-ayar"],
  ["A", "check-in saatini değiştirmek istiyorum", "checkin-ayar"],
  ["A", "kimlerin duyuruyu okuduğunu görmek istiyorum", "duyuru-kim-okudu"],
  ["A", "yardımcı antrenör sayısını artırmak istiyorum", "ayar-antrenor-limiti"],
  ["A", "gider eklemek istiyorum", "gelir-gider"],
  ["A", "kulüp verilerini excel olarak indirmek istiyorum", "disa-aktar"],
  ["A", "abonelik ekranı çıkıyor", "abonelik-durumu"],
  ["A", "sipariş nasıl teslim edildi olarak işaretlenir", "magaza-siparis-yonet"],
  ["K", "koordinatörün yetkileri neler", "roller-ozet"],
  ["C", "bugünkü antrenmanda kimler geldi işaretle", "yoklama-alma"],
  ["C", "yoklama ekranı kilitli", "yoklama-zaman-penceresi"],
  ["C", "maç skorunu kaydetmek istiyorum", "musabaka-sonuc"],
  ["C", "sporcunun boyunu kilosunu değiştir", "sporcu-duzenle-sil"],
  ["C", "sürat testi sonucu girmek istiyorum", "olcum-kaydet"],
  ["C", "hangi sporcu sakat", "sakatlik"],
  ["C", "gruba çalışma programı göndermek istiyorum", "fitness-grup-programi"],
  ["C", "sporcular uyku kayıtlarını doldurdu mu", "checkin-takip"],
  ["P", "aidat borcum ne kadar", "veli-aidat-ode"],
  ["P", "dekont nasıl yüklenir", "veli-aidat-ode"],
  ["P", "oğlum antrenmana gitmeyecek", "gelemeyecegim"],
  ["P", "kızımın yoklamasını görmek istiyorum", "yoklama-durumu"],
  ["P", "maç ne zaman", "takvim-veli-sporcu"],
  ["P", "forma almak istiyorum", "magaza-siparis"],
  ["P", "kampa kayıt olmak istiyorum", "etkinlik-kayit"],
  ["P", "hocaya yazmak istiyorum", "mesaj-gonder"],
  ["P", "giriş yapamıyorum şifrem yanlış diyor", "hesap-kilitlendi"],
  ["P", "hesabımı silmek istiyorum", "hesap-silme"],
  ["S", "bugün antrenman nasıl geçti puanla", "rpe-doldurma"],
  ["S", "uyku ve enerji kaydı girmek istiyorum", "checkin-doldurma"],
  ["S", "kendi programımı yazmak istiyorum", "fitness-sporcu-bireysel"],
  ["S", "ölçümlerim iyileşti mi", "olcum-gorme"],
  ["S", "en son kazandığım rozet", "rozet-nedir"],
  ["S", "arkadaşıma mesaj atmak istiyorum", "mesaj-kimle"],
  ["X", "kulüp aboneliği bitti", "sa-abonelik"],
  ["X", "bakım mesajı yazmak istiyorum", "sa-sistem-ayarlari"],
  ["ALL", "asistan gerçek yapay zeka mı", "asistan-nedir"],
  ["ALL", "uygulama çok yavaş açılıyor", "baglanti-sorunu"],
  ["ALL", "galeri izni vermiyor", "foto-izin"],
];

module.exports = { SAMPLES, NATURAL_TESTS };
